version: "3.1"

services:
  firebase-emulator:
    container_name: firebase-emulator
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 4000:4000 #Emulator UI
      - 9099:9099 #Firebase Auth
      - 9199:9199 #Firebase Cloud Storage
      - 9000:9000 #Firebase Realtime database
    environment:
      - FB_PROJECT_ID=evolute-test # Enter your Firebase project ID here
    volumes:
      # Firebase will export to `/firebase/data/export/`.
      # So in order to persist data, you should mount at least that volume.
      # Make sure to not explicitly mount to /firebase/data/export,
      # as the emulator will error with `Export failed: dest already exists`
      - ./firebase-data:/firebase/data:rw
